import { Component, OnInit, ElementRef, ViewChild, Inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { FormBuilder, FormGroup, FormArray, Validators, FormControl } from '@angular/forms';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { Observable, of } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { NgClass, NgFor, NgIf } from '@angular/common';
import { StatusColorPipe } from '../../shared/pipes/status-color.pipe';
import {
  Demande,
  TypeDemande,
  StatutDemande,
  MotifDemande,
  FichierJoint,
  Destinataire,
  MarqueMoto,
  TypeMoto,
} from '../../shared/models/demande.model';
import { DemandeService } from '../../shared/services/demande.service';
import { PdfService } from '../../shared/services/pdf.service';

@Component({
  selector: 'app-demande-form',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    NgIf,
    NgFor,
    NgClass,
    StatusColorPipe
  ],
  templateUrl: './demande-form.component.html',
  styleUrls: ['./demande-form.component.scss'],
  providers: [
    DemandeService,
    PdfService,
    ToastrService
  ]
})

export class DemandeFormComponent implements OnInit {
  @ViewChild('pdfContent') pdfContent!: ElementRef;

  // Component state
  today: Date = new Date();
  isEditMode = false;
  isViewMode = false;
  isLoading = false;

  // Form data properties
  quantite = 0;
  prix = 0;
  typeVendeur = '';
  typeBeneficiaire = '';
  typeAcheteur = '';
  marquemoto = MarqueMoto.YAMAHA;
  typemoto = TypeMoto.Moto;
  detailsComplementaires = '';
  numero = '';
  dateSoumission = new Date();
  nomImportateur = '';
  adresseImportateur = '';


  // Form group for the demande form
  demandeForm: FormGroup;

  // Form arrays for dynamic fields
  get documents(): FormArray {
    return this.demandeForm.get('documents') as FormArray;
  }

  // Current demande being edited/viewed
  demande: Partial<Demande> = {};

  // Enums for template access
  readonly TypeDemande = TypeDemande;
  readonly StatutDemande = StatutDemande;
  readonly MotifDemande = MotifDemande;
  readonly FichierJoint = FichierJoint;
  readonly Destinataire = Destinataire;
  readonly MarqueMoto = MarqueMoto;
  readonly TypeMoto = TypeMoto;

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private toastr: ToastrService,
    private demandeService: DemandeService,
    private pdfService: PdfService
  ) {
    this.demandeForm = this.fb.group({
      // Form controls will be added here
      documents: this.fb.array([])
    });
  }

  ngOnInit(): void {
    this.initializeForm();

    const id = this.route.snapshot.paramMap.get('id');
    const mode = this.route.snapshot.url[0]?.path;

    if (mode === 'view') {
      this.isViewMode = true;
    } else if (mode === 'edit') {
      this.isEditMode = true;
    }

    if (id) {
      this.loadDemande(+id);
    } else {
      this.initializeNewDemande();
    }
  }

  private initializeForm(): void {
    this.demandeForm = this.fb.group({
      // Basic information
      type: [TypeDemande.ACHAT, Validators.required],
      motif: [MotifDemande.COMMERCE, Validators.required],
      emetteur: ['', Validators.required],

      // Document information
      fichierJoint: [FichierJoint.FACTURE, Validators.required],

      // Importer information (legacy)
      nomImportateur: ['', Validators.required],
      adresseImportateur: ['', Validators.required],
      telephoneImportateur: ['', Validators.required],
      emailImportateur: ['', [Validators.required, Validators.email]],

      // Buyer information (legacy, optional)
      nomAcheteur: [''],
      adresseAcheteur: [''],
      telephoneAcheteur: [''],
      emailAcheteur: ['', Validators.email],

      // Additional information
      detailsComplementaires: [''],
      documentsFournis: this.fb.array([])

      // Moto information
      // marquemoto: [MarqueMoto.YAMAHA],
      // typemoto: [TypeMoto.Moto],
      // quantitemoto: [0],
      // prixmoto: [0],
      // valeurmoto: [0],
    });
  }

  private initializeNewDemande(): void {
    // Create a new Demande object with all required fields
    this.demande = {
      // Base information
      id: 0, // Will be set by the server
      numero: '', // Will be generated by the server
      type: TypeDemande.ACHAT,
      statut: StatutDemande.EN_ATTENTE,
      motif: MotifDemande.COMMERCE,
      emetteur: '',
      date: new Date(),
      dateSoumission: new Date(),
      dateTraitement: undefined,
      dateValidation: undefined,
      dateRejet: undefined,
      motifRejet: undefined,

      // Importer information (legacy)
      nomImportateur: '',
      adresseImportateur: '',
      telephoneImportateur: '',
      emailImportateur: '',

      // Buyer information (legacy, optional)
      nomAcheteur: '',
      adresseAcheteur: '',
      telephoneAcheteur: '',
      emailAcheteur: '',

      // Additional information
      detailsComplementaires: '',
      documentsFournis: [],

      // System fields
      utilisateurId: 1, // TODO: Get from auth service
      dateCreation: new Date(),
      dateMiseAJour: new Date(),

      // Initialize new structure (optional)
      importateur: undefined,
      acheteur: undefined,
      vendeur: undefined

      // Moto information
      // marquemoto: '',
      // typemoto: '',
      // quantitemoto: 0,
      // prixmoto: 0,
      // valeurmoto: 0,
    };

    // Patch form with default values
    this.demandeForm.patchValue(this.demande);

    if (this.isViewMode) {
      this.demandeForm.disable();
    }

    this.demandeForm.patchValue(this.demande);

    if (this.isViewMode) {
      this.demandeForm.disable();
    }
  }

  loadDemande(id: number): void {
    this.isLoading = true;
    this.demandeService.getDemande(id).pipe(
      catchError((error: any) => {
        console.error('Error loading demande:', error);
        this.toastr.error('Erreur lors du chargement de la demande', 'Erreur');
        this.isLoading = false;
        return of(null);
      })
    ).subscribe((data: Demande | null) => {
      this.isLoading = false;
      if (data) {
        // Ensure dates are properly converted from strings to Date objects
        const processedData: Demande = {
          ...data,
          date: new Date(data.date),
          dateSoumission: new Date(data.dateSoumission),
          dateCreation: new Date(data.dateCreation),
          dateMiseAJour: new Date(data.dateMiseAJour),
          dateTraitement: data.dateTraitement ? new Date(data.dateTraitement) : undefined,
          dateValidation: data.dateValidation ? new Date(data.dateValidation) : undefined,
          dateRejet: data.dateRejet ? new Date(data.dateRejet) : undefined
        };

        this.demande = processedData;
        this.demandeForm.patchValue(processedData);

        if (this.isViewMode) {
          this.demandeForm.disable();
        }
      }
    });
  }

  onSubmit(): void {
    if (this.demandeForm.invalid) {
      this.toastr.error('Veuillez remplir tous les champs obligatoires', 'Erreur');
      return;
    }

    this.isLoading = true;

    // Prepare the data for submission
    const formValue = this.demandeForm.value;
    const demandeData: Demande = {
      ...this.demande,
      ...formValue,
      // Ensure dates are properly set
      date: formValue.date || new Date(),
      dateMiseAJour: new Date(),
      // Ensure required arrays are initialized
      documentsFournis: formValue.documentsFournis || []
    };

    const demandeObservable = this.isEditMode
      ? this.demandeService.updateDemande(demandeData as Demande)
      : this.demandeService.createDemande(demandeData as unknown as Demande);

    demandeObservable.pipe(
      catchError((error: any) => {
        console.error('Error saving demande:', error);
        this.toastr.error(
          error.error?.message || 'Erreur lors de l\'enregistrement de la demande',
          'Erreur'
        );
        this.isLoading = false;
        return of(null);
      })
    ).subscribe((result: Demande | null) => {
      this.isLoading = false;
      if (result) {
        const message = this.isEditMode
          ? 'Demande mise à jour avec succès'
          : 'Demande créée avec succès';
        this.toastr.success(message, 'Succès');
        this.router.navigate(['/demandes']);
      }
    });
  }

  onCancel(): void {
    if (confirm('Voulez-vous vraiment annuler les modifications ?')) {
      if (this.demande.id) {
        this.loadDemande(this.demande.id);
      } else {
        this.router.navigate(['/demandes']);
      }
    }
  }

  // Method to view authorization
  voirAutorisation(): void {
    if (!this.demande) {
      this.toastr.error('Aucune demande sélectionnée', 'Erreur');
      return;
    }
    console.log('Viewing authorization for demande:', this.demande.id);
    // Add your authorization viewing logic here
  }

  // Method to add a document
  addDocument(type: string = '', fichier: File | null = null): void {
    this.documents.push(this.fb.group({
      type: [type, Validators.required],
      fichier: [fichier, Validators.required]
    }));
  }

  // Helper method to remove a document
  removeDocument(index: number): void {
    this.documents.removeAt(index);
  }
  onEdit(): void {
    this.isEditMode = true;
    this.isViewMode = false;
  }

  // Status helpers
  getStatusIcon(statut: StatutDemande | string | undefined): string {
    if (!statut) return 'help';

    switch (statut) {
      case StatutDemande.VALIDE:
        return 'check_circle';
      case StatutDemande.REJETE:
        return 'cancel';
      case StatutDemande.EN_ATTENTE:
        return 'schedule';
      case StatutDemande.TRAITE:
        return 'done_all';
      default:
        return 'help';
    }
  }

  getStatusText(statut: StatutDemande | string | undefined): string {
    if (!statut) return 'Inconnu';

    switch (statut) {
      case StatutDemande.VALIDE:
        return 'Validé';
      case StatutDemande.REJETE:
        return 'Rejeté';
      case StatutDemande.EN_ATTENTE:
        return 'En attente';
      case StatutDemande.TRAITE:
        return 'Traité';
      default:
        return statut;
    }
  }

  getStatusClass(statut: StatutDemande | string | undefined): string {
    if (!statut) return 'badge-secondary';

    switch (statut) {
      case StatutDemande.VALIDE:
        return 'badge-success';
      case StatutDemande.REJETE:
        return 'badge-danger';
      case StatutDemande.EN_ATTENTE:
        return 'badge-warning';
      case StatutDemande.TRAITE:
        return 'badge-info';
      default:
        return 'badge-secondary';
    }
  }
}
